language: python
python:
 - "2.6"
 - "2.7"
 - "3.2"
 - "3.3"
 - "3.2"
 - "3.4"
 - "pypy"
 - "pypy3"
 - "nightly" # Cython
install: "pip install nose && pip install coverage"
script: "nosetests && coverage report --fail-under=80"
